version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-02-03T21-03-04Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  mc:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set myminio http://minio:9000 admin password123;
        mc mb -p myminio/bronze;
        mc cp /dados/* myminio/bronze/;
        tail -f /dev/null
      "
    volumes:
      - ./dados/bronze:/dados

volumes:
  minio_data: